---

# tasks file

- name: ensure nginx is at the latest version
  apt:
          name: nginx
          state: latest

- name: start nginx service
  service:
          name: nginx
          state: started
          enabled: yes

- name: set confing file
  template:
          src: nginx.conf
          dest: /etc/nginx/nginx.conf
  notify: restart nginx
