---
# frontend playbook
- name: "Provisioning fronted server"
  hosts: tag_Name_jenkins:&tag_Environment_Test
  become: yes
  become_method: sudo
  roles:
          - jenkins
          - docker
          - kubernetes
