---
- name: "Provisioning jenkins server"
  hosts: tag_Name_jenkins:&tag_Environment_Test
  become: yes
  become_user: root
  become_method: sudo
  roles:
          - jenkins
          - docker
          - kubernetes

- name: "Provisioning backend server"
  hosts: tag_Name_backend:&tag_Environment_Test
  become: yes
  become_user: root
  become_method: sudo
  roles:
          - nodejs_api
          - mysql_client

- name: "Provisioning fronted server"
  hosts: tag_Name_fronted:&tag_Environment_Test
  become: yes
  become_user: root
  become_method: sudo
  roles:
          - nodejs_ui

- name: "Provisioning proxy server with nginx"
  hosts: tag_Name_nginx_proxy:&tag_Environment_Test
  become: yes
  become_user: root
  become_method: sudo
  roles:
          - nginx
