---
#tasks file

- name: "Installing apt dependencies"
  apt:
          name: "{{ item }}"
  with_items:
          - python-mysqldb
          - mysql-server-core-8.0
          - python-dev 
          - libmysqlclient-dev
          - mysql-client
          - python-pip
          - build-essential

- name: Install the MySQL-python through pip
  pip:
          name: "{{ item }}"
  state: forcereinstall
  with_items:
          - pip
          - MySQL-python

- name: set default auth method to mysql_native_password
  lineinfile:
          dest: "{{ my_conf_path }}"
          insertafter: '[mysqld]'
          line: 'default-auth=mysql_native_password'

- name: Copy init.sql script
  template:
          src: init.sql
          dest: "{{ home_path }}"
          mode: 0775

- name: execute sql script
  mysql_db:
          login_host: "{{ db_host }}"
          login_user: "{{ db_user }}"
          login_password: "{{ db_pass }}"
          state: import
          name: all
          target: "{{ home_path }}/init.sql"
