---
# tasks file

- name: Install Docker
  ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh

    - name: Build Docker Jenkins Image
    docker_image:
      name: jenkins-docker
      build:
        path: .
        pull: "yes"
      source: build
      state: present

- name: Create Docker Jenkins Container
  docker_container:
     name: "{{ container_name }}"
     image: jenkins-docker
     ports:
      - "8080:8080"
      - "50000:50000"
     volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
     state: started