---
# tasks file

- name: Install apt-transport-https
ansible.builtin.apt:
  name:
    - apt-transport-https
    - ca-certificates
    - lsb-release
    - gnupg
  state: latest
  update_cache: true

- name: see Linux Standard Base to add docker repo
  command: lsb_release -cs
  register: lsb_release

- name: see register result
  debug:
          msg: "the lsb for this instance is: {{ lsb_release.stdout }}"

- name: Add signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ lsb_release.stdout }} stable"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: true

- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/jenkins

- name: Pull the latest official jenkins docker image
  docker_image:
    name: "jenkins:latest"

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: "jenkins"
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - "/share/jenkins:/var/jenkins_home"
    state: present
    recreate: no
