---
# tasks file

- name: Add Docker Group
  group: name=docker state=present

- name: add docker engine official gpg key
  apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

- name: see Linux Standard Base to add docker repo
  command: lsb_release -cs
  register: lsb_release

- name: see register result
  debug:
          msg: "the lsb for this instance is: {{ lsb_release.stdout }}"

- name: setting up a stable repository
  apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
          state: present
          update_cache: yes

- name: Install Docker
  apt: name=docker-engine state=present
        
- name: Install docker-py
  pip: name=docker-py version=1.9.0

  - name: Ensure jenkins directory on docker host
    file:
      state: directory
      owner: 1000
      group: 1000
      path: /share/jenkins

- name: Pull the latest official jenkins docker image
  docker_image:
    name: "jenkins:latest"

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: "jenkins"
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - "/share/jenkins:/var/jenkins_home"
    state: present
    recreate: no
